---
- name: Run simple Flask server for andersen course
  hosts: debian
  become: yes

  vars:
    work_folder: /Flask

  tasks:
    - name: install packages
      apt: name={{item}} state=latest
      with_items:
        - python3-pip
        - python3-venv
        - python-virtualenv

    - name: Delete content & directory
      file:
        state: absent
        path: "{{work_folder}}"

    - name: Creates directory
      file:
        path: "{{work_folder}}"
        state: directory

    # - name: clone repo
    #   git:
    #     repo: "https://github.com/vacilyok/Simple-Flask.git"
    #     dest: "{{work_folder}}"
    #     update: yes

    - name: Copy server.py file
      copy:
        src: server.py
        dest: "{{work_folder}}/app.py"
        mode: "0644"

    - name: Manually create the initial virtualenv
      command:
        cmd: virtualenv /Flask/myenv -p python3.7
        creates: "/Flask/myenv"

    - name: install Flask
      shell: /Flask/myenv/bin/pip install Flask

    - name: install waitress
      shell: /Flask/myenv/bin/pip install waitress

    # - name: Run server
    #   shell: /Flask/myenv/bin/python3.7 /Flask/app.py
    #   async: 1000
    #   poll: 0

    - name: template systemd service config
      template:
        src: service.j2
        dest: /etc/systemd/system/flask.service
        mode: "0644"

    - name: start systemd app service
      systemd: name=flask.service daemon_reload=yes state=started enabled=yes
