---
- name: Run simple Flask server for andersen course
  hosts: debian
  become: yes

  vars:
    work_folder: /Flask

  tasks:
    - authorized_key:
        user: "{{ansible_ssh_user}}"
        state: present
        manage_dir: yes
        key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

    - name: install packages
      apt: name={{item}} state=latest
      with_items:
        - python3-pip
        - python3-venv
        - python-virtualenv
        - ufw

    - name: Replace a localhost
      lineinfile:
        path: /etc/hosts
        regexp: '^127\.0\.0\.1'
        line: 127.0.0.1 {{ansible_hostname}}.localhost localhost

    - name: Delete content & directory
      file:
        state: absent
        path: "{{work_folder}}"

    - name: Creates directory
      file:
        path: "{{work_folder}}"
        state: directory

    # - name: clone repo
    #   git:
    #     repo: "https://github.com/vacilyok/Simple-Flask.git"
    #     dest: "{{work_folder}}"
    #     update: yes

    - name: Copy server.py file
      copy:
        src: server.py
        dest: "{{work_folder}}/app.py"
        mode: "0644"

    - name: Manually create the initial virtualenv
      command:
        cmd: virtualenv /Flask/myenv -p python3.7
        creates: "/Flask/myenv"

    - name: install Flask
      shell: /Flask/myenv/bin/pip install Flask

    - name: install waitress
      shell: /Flask/myenv/bin/pip install waitress

    - name: template systemd service config
      template:
        src: service.j2
        dest: /etc/systemd/system/flask.service
        mode: "0644"

    - name: start systemd app service
      systemd: name=flask.service daemon_reload=yes state=started enabled=yes

    - name: Allow SSH in UFW
      ufw: rule=allow port=22 proto=tcp

    - name: Allow http in UFW
      ufw: rule=allow port=80 proto=tcp

    - name: Set firewall default policy
      ufw: state=enabled policy=reject

    - name: Disable root login
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin "
        line: PermitRootLogin no

    - name: Disable password authentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PasswordAuthentication yes"
        line: PasswordAuthentication  no

    - name: Disable UsePAM
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^UsePAM yes"
        line: UsePAM no

    - name: Disable ChallengeResponseAuthentication
      lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^ChallengeResponseAuthentication yes"
        line: ChallengeResponseAuthentication no

    - name: Stop and Start ssh
      service:
        name: ssh
        state: restarted
